server {
    listen 8443 ssl;
    server_name env-fixture localhost;

    ssl_certificate /etc/nginx/certs/env-fixture.crt;
    ssl_certificate_key /etc/nginx/certs/env-fixture.key;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        autoindex on;
        try_files $uri =404;
    }
}
