freeStyleJob('jobdsl-remote-env-wrapper-success') {
  description('Generated by the Job DSL seed job. Native remoteEnvFiles wrapper example using helper and nested source styles. See examples/jobdsl/README.md for the canonical syntax reference.')

  wrappers {
    remoteEnvFiles {
      source('https://env-fixture:8443/base.env', 'fixture-bearer')
      source {
        sourceUrl('https://env-fixture:8443/prod.env')
        credentialsId('fixture-basic')
      }
    }
  }

  steps {
    shell('''#!/bin/sh -eu
test "$APP_NAME" = "remote-env-file-demo"
test "$APP_MODE" = "prod"
test "$COMMON_VALUE" = "prod-override"
test "$RELEASE_CHANNEL" = "stable"
echo "Job DSL wrapper example passed"
''')
  }
}
