pipelineJob('jobdsl-remote-env-configure-fallback') {
  description('Generated by the Job DSL seed job. Configure-block fallback example for the Pipeline job property. See examples/jobdsl/README.md for the canonical syntax reference.')

  configure { project ->
    def properties = project / 'properties'
    properties << 'io.jenkins.plugins.remoteenvfile.RemoteEnvFileJobProperty' {
      sources {
        'io.jenkins.plugins.remoteenvfile.RemoteEnvSource' {
          sourceUrl('https://env-fixture:8443/base.env')
        }
        'io.jenkins.plugins.remoteenvfile.RemoteEnvSource' {
          sourceUrl('https://env-fixture:8443/prod.env')
        }
      }
    }
  }

  definition {
    cps {
      sandbox(true)
      script('''pipeline {
  agent any

  stages {
    stage('Verify Configure Fallback') {
      steps {
        sh 'test "$APP_MODE" = "prod"'
        sh 'test "$COMMON_VALUE" = "prod-override"'
        sh 'echo "Job DSL configure fallback example passed"'
      }
    }
  }
}''')
    }
  }
}
