pipelineJob('jobdsl-remote-env-pipeline-property-success') {
  description('Generated by the Job DSL seed job. Native remoteEnvFiles job-property example with layered sources. See examples/jobdsl/README.md for the canonical syntax reference.')

  properties {
    remoteEnvFiles {
      source {
        sourceUrl('https://env-fixture:8443/base.env')
      }
      source('https://env-fixture:8443/prod.env')
    }
  }

  definition {
    cps {
      sandbox(true)
      script('''pipeline {
  agent any

  stages {
    stage('Verify Job DSL Property') {
      steps {
        sh 'test "$APP_NAME" = "remote-env-file-demo"'
        sh 'test "$APP_MODE" = "prod"'
        sh 'test "$COMMON_VALUE" = "prod-override"'
        sh 'echo "Job DSL pipeline property example passed"'
      }
    }
  }
}''')
    }
  }
}
